void pins() {
  Serial.begin(115200);
  Serial1.begin(115200);
  Serial2.begin(115200);
  myServo.attach(9);
  PIDX.SetMode(AUTOMATIC);
  //PIDY.SetMode(AUTOMATIC);
  PIDX.SetOutputLimits(-255, 255);
  //PIDY.SetOutputLimits(-255, 255);
  attachInterrupt(digitalPinToInterrupt(pin), InterruptFunction, HIGH);
  pinMode(13, OUTPUT);
  pinMode(pin, INPUT);
  pinMode(dcm1, OUTPUT);
  pinMode(dcm2, OUTPUT);
  pinMode(dcm3, OUTPUT);
  pinMode(dcm4, OUTPUT);
  pinMode(pin1, OUTPUT);
  pinMode(pin2, OUTPUT);
  pinMode(pin3, OUTPUT);
  pinMode(pin4, OUTPUT);
  pinMode(johnsonr1, OUTPUT);
  pinMode(johnsonr2, OUTPUT);
  pinMode(johnsonl1, OUTPUT);
  pinMode(johnsonl2, OUTPUT);
  pinMode(limitswitch1, INPUT);
  pinMode(limitswitch2, INPUT);
  pinMode(limitswitch3, INPUT);
  pinMode(limitswitch4, INPUT);
  pinMode(limitswitch5, INPUT);
  pinMode(limitswitch6, INPUT);
  pinMode(limitswitch7, INPUT);
  pinMode(limitswitch8, INPUT);
  pinMode(limitswitch9, INPUT);
  pinMode(limitswitch10, INPUT);
  stepper1.setMaxSpeed(2000);
  stepper1.setAcceleration(3000);
  stepper2.setMaxSpeed(2000);
  stepper2.setAcceleration(3000);
  stepper3.setMaxSpeed(2000);
  stepper3.setAcceleration(3000);
  stepper4.setMaxSpeed(2000);
  stepper4.setAcceleration(3000);
  pinMode(stepPin1, OUTPUT);
  pinMode(dirPin1, OUTPUT);
  pinMode(stepPin2, OUTPUT);
  pinMode(dirPin2, OUTPUT);
  pinMode(stepPin3, OUTPUT);
  pinMode(dirPin3, OUTPUT);
  pinMode(stepPin4, OUTPUT);
  pinMode(dirPin4, OUTPUT);
  esc1.attach(9);
  esc1.write(30);
  esc2.attach(8);
  esc2.write(30);
  esc3.attach(7);
  esc3.write(30);
  esc4.attach(6);
  esc4.write(30);
  delay(1000);
  myServo.write(90);
}